### ISSUE TITLE
Ported your development to TypeTopology

### ISSUE THREAD

**Issue by martinescardo** [BrendanHart/Investigating-Properties-of-PCF#1]
Hi @BrendanHart 

This is not really an issue. It is just to let you know that I've ported this to https://github.com/martinescardo/TypeTopology

See the folder https://github.com/martinescardo/TypeTopology/tree/master/source/PCF

**Comment by BrendanHart** [comment]
Great, thanks @martinescardo!

**Comment by martinescardo** [comment]
NB. If you want to see the html rendering of your code in TypeTopology, it is here:

https://www.cs.bham.ac.uk/~mhe/TypeTopology/PCF.Lambda.index.html
